<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Event;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $events = [
            [
                'category_id' => 2, // Budaya
                'name' => 'Sekaten',
                'slug' => 'sekaten',
                'description' => 'Sekaten adalah upacara tradisional Jawa yang diadakan untuk memperingati Maulid Nabi Muhammad SAW. Acara ini berlangsung selama seminggu dengan berbagai kegiatan budaya.',
                'location' => 'Keraton Surakarta',
                'address' => 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta',
                'latitude' => -7.5833,
                'longitude' => 110.8264,
                'image' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
                'rating' => 4.9,
                'total_reviews' => 456,
                'start_date' => Carbon::now()->addMonths(2)->startOfMonth()->addDays(11),
                'end_date' => Carbon::now()->addMonths(2)->startOfMonth()->addDays(19),
                'start_time' => '08:00:00',
                'end_time' => '22:00:00',
                'organizer' => 'Keraton Surakarta',
                'contact' => '0271-123456',
                'ticket_price' => 'Free',
                'is_free' => true,
                'is_featured' => true,
                'views' => 892,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Solo Batik Carnival',
                'slug' => 'solo-batik-carnival',
                'description' => 'Solo Batik Carnival adalah karnaval fashion batik terbesar di Indonesia. Peserta mengenakan kostum batik yang spektakuler dan berjalan di sepanjang Jl. Slamet Riyadi.',
                'location' => 'Jl. Slamet Riyadi',
                'address' => 'Jl. Slamet Riyadi, Kota Surakarta',
                'latitude' => -7.5689,
                'longitude' => 110.8156,
                'image' => 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800',
                'rating' => 4.8,
                'total_reviews' => 678,
                'start_date' => Carbon::now()->addMonths(3)->startOfMonth()->addDays(14),
                'end_date' => Carbon::now()->addMonths(3)->startOfMonth()->addDays(14),
                'start_time' => '18:00:00',
                'end_time' => '22:00:00',
                'organizer' => 'Pemkot Surakarta',
                'contact' => '0271-234567',
                'ticket_price' => 'Free',
                'is_free' => true,
                'is_featured' => true,
                'views' => 1543,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Grebeg Sudiro',
                'slug' => 'grebeg-sudiro',
                'description' => 'Grebeg Sudiro adalah perayaan Tahun Baru Imlek yang diadakan di kawasan Pasar Gede. Acara ini menampilkan barongsai, tarian naga, dan berbagai pertunjukan budaya Tionghoa.',
                'location' => 'Pasar Gede',
                'address' => 'Jl. Urip Sumoharjo, Pasar Gede, Kota Surakarta',
                'latitude' => -7.5712,
                'longitude' => 110.8267,
                'image' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800',
                'rating' => 4.7,
                'total_reviews' => 523,
                'start_date' => Carbon::now()->addMonths(1)->startOfMonth()->addDays(0),
                'end_date' => Carbon::now()->addMonths(1)->startOfMonth()->addDays(0),
                'start_time' => '10:00:00',
                'end_time' => '18:00:00',
                'organizer' => 'Paguyuban Sudiro',
                'contact' => '0271-345678',
                'ticket_price' => 'Free',
                'is_free' => true,
                'is_featured' => true,
                'views' => 1234,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Solo International Performing Arts',
                'slug' => 'solo-international-performing-arts',
                'description' => 'SIPA adalah festival seni pertunjukan internasional yang menampilkan seniman dari berbagai negara. Festival ini menampilkan teater, tari, musik, dan seni pertunjukan lainnya.',
                'location' => 'Taman Budaya Surakarta',
                'address' => 'Jl. Ir. Sutami No. 57, Kota Surakarta',
                'latitude' => -7.5645,
                'longitude' => 110.8198,
                'image' => 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
                'rating' => 4.6,
                'total_reviews' => 345,
                'start_date' => Carbon::now()->addMonths(4)->startOfMonth()->addDays(19),
                'end_date' => Carbon::now()->addMonths(4)->startOfMonth()->addDays(26),
                'start_time' => '19:00:00',
                'end_time' => '22:00:00',
                'organizer' => 'Taman Budaya Surakarta',
                'contact' => '0271-456789',
                'ticket_price' => 'Rp 50.000 - 150.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 678,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Festival Gamelan Internasional',
                'slug' => 'festival-gamelan-internasional',
                'description' => 'Festival gamelan yang menampilkan grup gamelan dari berbagai negara. Acara ini menjadi ajang pertukaran budaya dan apresiasi seni gamelan.',
                'location' => 'ISI Surakarta',
                'address' => 'Jl. Ki Hajar Dewantara No. 19, Surakarta',
                'latitude' => -7.5456,
                'longitude' => 110.8234,
                'image' => 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
                'rating' => 4.8,
                'total_reviews' => 234,
                'start_date' => Carbon::now()->addMonths(5)->startOfMonth()->addDays(10),
                'end_date' => Carbon::now()->addMonths(5)->startOfMonth()->addDays(15),
                'start_time' => '19:00:00',
                'end_time' => '22:00:00',
                'organizer' => 'ISI Surakarta',
                'contact' => '0271-567890',
                'ticket_price' => 'Rp 25.000 - 75.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 567,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Pasar Malam Ngarsopuro',
                'slug' => 'pasar-malam-ngarsopuro',
                'description' => 'Pasar malam yang diadakan setiap akhir pekan di kawasan Ngarsopuro. Menampilkan berbagai kuliner, kerajinan, dan pertunjukan musik.',
                'location' => 'Ngarsopuro',
                'address' => 'Jl. Diponegoro, Ngarsopuro, Surakarta',
                'latitude' => -7.5723,
                'longitude' => 110.8245,
                'image' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
                'rating' => 4.5,
                'total_reviews' => 789,
                'start_date' => Carbon::now()->addDays(5),
                'end_date' => Carbon::now()->addDays(6),
                'start_time' => '18:00:00',
                'end_time' => '23:00:00',
                'organizer' => 'Komunitas Ngarsopuro',
                'contact' => '0271-678901',
                'ticket_price' => 'Free',
                'is_free' => true,
                'is_featured' => true,
                'views' => 1234,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Solo Jazz Festival',
                'slug' => 'solo-jazz-festival',
                'description' => 'Festival jazz tahunan yang menampilkan musisi jazz lokal dan internasional. Acara ini diadakan di berbagai venue di Solo.',
                'location' => 'Benteng Vastenburg',
                'address' => 'Jl. Kapten Mulyadi, Kedung Lumbu, Surakarta',
                'latitude' => -7.5645,
                'longitude' => 110.8198,
                'image' => 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
                'rating' => 4.7,
                'total_reviews' => 456,
                'start_date' => Carbon::now()->addMonths(6)->startOfMonth()->addDays(20),
                'end_date' => Carbon::now()->addMonths(6)->startOfMonth()->addDays(22),
                'start_time' => '19:00:00',
                'end_time' => '23:00:00',
                'organizer' => 'Solo Jazz Community',
                'contact' => '0271-789012',
                'ticket_price' => 'Rp 75.000 - 200.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 987,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Wayang Kulit Dalang Ki Manteb',
                'slug' => 'wayang-kulit-dalang-ki-manteb',
                'description' => 'Pertunjukan wayang kulit oleh dalang terkenal Ki Manteb Sudarsono. Menampilkan cerita Ramayana dengan gamelan lengkap.',
                'location' => 'Pendopo Taman Sriwedari',
                'address' => 'Jl. Slamet Riyadi, Sriwedari, Surakarta',
                'latitude' => -7.5689,
                'longitude' => 110.8156,
                'image' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
                'rating' => 4.9,
                'total_reviews' => 345,
                'start_date' => Carbon::now()->addDays(15),
                'end_date' => Carbon::now()->addDays(15),
                'start_time' => '20:00:00',
                'end_time' => '05:00:00',
                'organizer' => 'Taman Sriwedari',
                'contact' => '0271-890123',
                'ticket_price' => 'Rp 15.000 - 50.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 678,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Festival Kuliner Solo',
                'slug' => 'festival-kuliner-solo',
                'description' => 'Festival kuliner yang menampilkan berbagai makanan khas Solo dan Jawa Tengah. Acara ini diadakan di alun-alun utara Keraton.',
                'location' => 'Alun-alun Utara',
                'address' => 'Alun-alun Utara, Baluwarti, Surakarta',
                'latitude' => -7.5812,
                'longitude' => 110.8278,
                'image' => 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
                'rating' => 4.6,
                'total_reviews' => 567,
                'start_date' => Carbon::now()->addMonths(2)->startOfMonth()->addDays(5),
                'end_date' => Carbon::now()->addMonths(2)->startOfMonth()->addDays(7),
                'start_time' => '16:00:00',
                'end_time' => '22:00:00',
                'organizer' => 'Dinas Pariwisata Solo',
                'contact' => '0271-901234',
                'ticket_price' => 'Free',
                'is_free' => true,
                'is_featured' => true,
                'views' => 1456,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Pameran Batik Nusantara',
                'slug' => 'pameran-batik-nusantara',
                'description' => 'Pameran batik dari berbagai daerah di Indonesia. Menampilkan koleksi batik antik dan kontemporer dari seluruh nusantara.',
                'location' => 'Museum Batik Danar Hadi',
                'address' => 'Jl. Slamet Riyadi No. 261, Surakarta',
                'latitude' => -7.5678,
                'longitude' => 110.8123,
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
                'rating' => 4.4,
                'total_reviews' => 234,
                'start_date' => Carbon::now()->addMonths(3)->startOfMonth()->addDays(1),
                'end_date' => Carbon::now()->addMonths(3)->startOfMonth()->addDays(30),
                'start_time' => '09:00:00',
                'end_time' => '16:00:00',
                'organizer' => 'Museum Batik Danar Hadi',
                'contact' => '0271-012345',
                'ticket_price' => 'Rp 20.000 - 35.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 789,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Konser Musik Tradisional',
                'slug' => 'konser-musik-tradisional',
                'description' => 'Konser musik tradisional Jawa yang menampilkan berbagai alat musik gamelan dan tembang Jawa. Diadakan di Pendopo Mangkunegaran.',
                'location' => 'Pura Mangkunegaran',
                'address' => 'Jl. Ronggowarsito No.150, Keprabon, Surakarta',
                'latitude' => -7.5697,
                'longitude' => 110.8114,
                'image' => 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
                'rating' => 4.7,
                'total_reviews' => 345,
                'start_date' => Carbon::now()->addDays(25),
                'end_date' => Carbon::now()->addDays(25),
                'start_time' => '19:30:00',
                'end_time' => '22:00:00',
                'organizer' => 'Pura Mangkunegaran',
                'contact' => '0271-123456',
                'ticket_price' => 'Rp 30.000 - 75.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 567,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Festival Tari Tradisional',
                'slug' => 'festival-tari-tradisional',
                'description' => 'Festival tari tradisional yang menampilkan berbagai tarian dari Jawa Tengah dan daerah lainnya. Acara ini diadakan di Taman Budaya Surakarta.',
                'location' => 'Taman Budaya Surakarta',
                'address' => 'Jl. Ir. Sutami No. 57, Kota Surakarta',
                'latitude' => -7.5645,
                'longitude' => 110.8198,
                'image' => 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
                'rating' => 4.8,
                'total_reviews' => 456,
                'start_date' => Carbon::now()->addMonths(4)->startOfMonth()->addDays(8),
                'end_date' => Carbon::now()->addMonths(4)->startOfMonth()->addDays(10),
                'start_time' => '19:00:00',
                'end_time' => '21:30:00',
                'organizer' => 'Taman Budaya Surakarta',
                'contact' => '0271-234567',
                'ticket_price' => 'Rp 25.000 - 60.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 890,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Solo Book Fair',
                'slug' => 'solo-book-fair',
                'description' => 'Pameran buku tahunan yang menampilkan berbagai penerbit lokal dan nasional. Acara ini juga menampilkan diskusi buku dan bedah buku.',
                'location' => 'Solo Grand Mall',
                'address' => 'Jl. Slamet Riyadi No. 451, Pajang, Surakarta',
                'latitude' => -7.5456,
                'longitude' => 110.8345,
                'image' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
                'rating' => 4.3,
                'total_reviews' => 234,
                'start_date' => Carbon::now()->addMonths(5)->startOfMonth()->addDays(15),
                'end_date' => Carbon::now()->addMonths(5)->startOfMonth()->addDays(20),
                'start_time' => '10:00:00',
                'end_time' => '21:00:00',
                'organizer' => 'Ikatan Penerbit Indonesia',
                'contact' => '0271-345678',
                'ticket_price' => 'Free',
                'is_free' => true,
                'is_featured' => true,
                'views' => 456,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Workshop Batik untuk Pemula',
                'slug' => 'workshop-batik-untuk-pemula',
                'description' => 'Workshop membatik untuk pemula yang diadakan di Kampung Batik Laweyan. Peserta akan belajar teknik dasar membatik dari pengrajin berpengalaman.',
                'location' => 'Kampung Batik Laweyan',
                'address' => 'Jl. Dr. Rajiman, Laweyan, Surakarta',
                'latitude' => -7.5834,
                'longitude' => 110.8123,
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
                'rating' => 4.6,
                'total_reviews' => 123,
                'start_date' => Carbon::now()->addDays(12),
                'end_date' => Carbon::now()->addDays(12),
                'start_time' => '09:00:00',
                'end_time' => '15:00:00',
                'organizer' => 'Paguyuban Batik Laweyan',
                'contact' => '0271-456789',
                'ticket_price' => 'Rp 150.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 345,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Pertunjukan Kethoprak',
                'slug' => 'pertunjukan-kethoprak',
                'description' => 'Pertunjukan kethoprak tradisional dengan cerita sejarah Jawa. Diadakan di Gedung Wayang Orang Sriwedari setiap malam Minggu.',
                'location' => 'Gedung Wayang Orang Sriwedari',
                'address' => 'Jl. Slamet Riyadi, Sriwedari, Surakarta',
                'latitude' => -7.5689,
                'longitude' => 110.8156,
                'image' => 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
                'rating' => 4.5,
                'total_reviews' => 178,
                'start_date' => Carbon::now()->addDays(10),
                'end_date' => Carbon::now()->addDays(10),
                'start_time' => '20:00:00',
                'end_time' => '23:00:00',
                'organizer' => 'Sriwedari Theater',
                'contact' => '0271-567890',
                'ticket_price' => 'Rp 10.000 - 25.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 234,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Solo Heritage Walk',
                'slug' => 'solo-heritage-walk',
                'description' => 'Tur jalan kaki mengunjungi situs-situs bersejarah di Solo. Dipandu oleh guide berpengalaman yang menjelaskan sejarah dan budaya Solo.',
                'location' => 'Keraton Surakarta',
                'address' => 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta',
                'latitude' => -7.5833,
                'longitude' => 110.8264,
                'image' => 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
                'rating' => 4.7,
                'total_reviews' => 289,
                'start_date' => Carbon::now()->addDays(8),
                'end_date' => Carbon::now()->addDays(8),
                'start_time' => '08:00:00',
                'end_time' => '12:00:00',
                'organizer' => 'Solo Heritage Society',
                'contact' => '0271-678901',
                'ticket_price' => 'Rp 50.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 567,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Festival Fotografi Solo',
                'slug' => 'festival-fotografi-solo',
                'description' => 'Festival fotografi yang menampilkan karya fotografer lokal dan nasional. Acara ini juga mengadakan workshop dan kompetisi foto.',
                'location' => 'Benteng Vastenburg',
                'address' => 'Jl. Kapten Mulyadi, Kedung Lumbu, Surakarta',
                'latitude' => -7.5645,
                'longitude' => 110.8198,
                'image' => 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800',
                'rating' => 4.4,
                'total_reviews' => 156,
                'start_date' => Carbon::now()->addMonths(6)->startOfMonth()->addDays(5),
                'end_date' => Carbon::now()->addMonths(6)->startOfMonth()->addDays(12),
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'organizer' => 'Solo Photography Club',
                'contact' => '0271-789012',
                'ticket_price' => 'Free',
                'is_free' => true,
                'is_featured' => true,
                'views' => 345,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Konser Musik Keroncong',
                'slug' => 'konser-musik-keroncong',
                'description' => 'Konser musik keroncong yang menampilkan grup keroncong terkenal dari Solo dan sekitarnya. Diadakan di Taman Balekambang.',
                'location' => 'Taman Balekambang',
                'address' => 'Jl. Balekambang, Manahan, Kec. Banjarsari, Kota Surakarta',
                'latitude' => -7.5589,
                'longitude' => 110.8456,
                'image' => 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
                'rating' => 4.6,
                'total_reviews' => 234,
                'start_date' => Carbon::now()->addDays(18),
                'end_date' => Carbon::now()->addDays(18),
                'start_time' => '19:00:00',
                'end_time' => '22:00:00',
                'organizer' => 'Komunitas Keroncong Solo',
                'contact' => '0271-890123',
                'ticket_price' => 'Rp 20.000 - 40.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 456,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Pagelaran Seni Mahasiswa',
                'slug' => 'pagelaran-seni-mahasiswa',
                'description' => 'Pagelaran seni yang menampilkan karya mahasiswa dari berbagai perguruan tinggi di Solo. Menampilkan teater, tari, musik, dan seni rupa.',
                'location' => 'ISI Surakarta',
                'address' => 'Jl. Ki Hajar Dewantara No. 19, Surakarta',
                'latitude' => -7.5456,
                'longitude' => 110.8234,
                'image' => 'https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800',
                'rating' => 4.3,
                'total_reviews' => 167,
                'start_date' => Carbon::now()->addMonths(3)->startOfMonth()->addDays(25),
                'end_date' => Carbon::now()->addMonths(3)->startOfMonth()->addDays(27),
                'start_time' => '18:00:00',
                'end_time' => '21:00:00',
                'organizer' => 'ISI Surakarta',
                'contact' => '0271-901234',
                'ticket_price' => 'Rp 15.000 - 30.000',
                'is_free' => false,
                'is_featured' => true,
                'views' => 289,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Solo Design Week',
                'slug' => 'solo-design-week',
                'description' => 'Pekan desain yang menampilkan karya desainer lokal dan nasional. Acara ini mengadakan pameran, workshop, dan seminar tentang desain.',
                'location' => 'Solo Paragon Mall',
                'address' => 'Jl. Yosodipuro No. 135, Surakarta',
                'latitude' => -7.5567,
                'longitude' => 110.8234,
                'image' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
                'rating' => 4.5,
                'total_reviews' => 198,
                'start_date' => Carbon::now()->addMonths(7)->startOfMonth()->addDays(10),
                'end_date' => Carbon::now()->addMonths(7)->startOfMonth()->addDays(17),
                'start_time' => '10:00:00',
                'end_time' => '21:00:00',
                'organizer' => 'Solo Design Community',
                'contact' => '0271-012345',
                'ticket_price' => 'Free',
                'is_free' => true,
                'is_featured' => true,
                'views' => 378,
            ],
        ];

        foreach ($events as $event) {
            Event::firstOrCreate(['slug' => $event['slug']], $event);
        }
    }
}