<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Culinary;

class CulinarySeeder extends Seeder
{
    public function run(): void
    {
        $culinaries = [
            [
                'category_id' => 3, // Kuliner
                'name' => 'Nasi Liwet Wongso Lemu',
                'slug' => 'nasi-liwet-wongso-lemu',
                'description' => 'Nasi liwet legendaris yang sudah berdiri sejak tahun 1950. Disajikan dengan lauk ayam suwir, telur, dan sambal yang khas.',
                'location' => 'Jl. Teuku Umar',
                'address' => 'Jl. Teuku Umar No. 123, Solo',
                'latitude' => -7.5678,
                'longitude' => 110.8234,
                'image' => 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800',
                'rating' => 0.0,
                'total_reviews' =>0,
                'price_range' => 'Rp 15.000 - 35.000',
                'since' => 'Sejak 1950',
                'facilities' => 'Parking, Dine-in, Takeaway',
                'highlights' => 'Legendary recipe, Traditional taste, Family friendly',
                'opening_hours' => '10:00 - 22:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 3421,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Sate Buntel Mbok Galak',
                'slug' => 'sate-buntel-mbok-galak',
                'description' => 'Sate buntel khas Solo yang terbuat dari daging kambing cincang yang dibungkus lemak kambing. Rasanya gurih dan lezat.',
                'location' => 'Pasar Gede',
                'address' => 'Pasar Gede, Jl. Urip Sumoharjo, Solo',
                'latitude' => -7.5712,
                'longitude' => 110.8267,
                'image' => 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 25.000 - 50.000',
                'since' => 'Sejak 1975',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Authentic satay, Spicy sauce, Traditional recipe',
                'opening_hours' => '09:00 - 21:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 2987,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Timlo Sastro',
                'slug' => 'timlo-sastro',
                'description' => 'Timlo adalah sup khas Solo yang berisi sosis solo, telur, dan sayuran. Timlo Sastro adalah yang paling terkenal di Solo.',
                'location' => 'Jl. Kapten Mulyadi',
                'address' => 'Jl. Kapten Mulyadi No. 89, Solo',
                'latitude' => -7.5645,
                'longitude' => 110.8198,
                'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 20.000 - 40.000',
                'since' => 'Sejak 1960',
                'facilities' => 'Parking, Dine-in, AC',
                'highlights' => 'Solo specialty, Homemade sausage, Rich broth',
                'opening_hours' => '08:00 - 20:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 1654,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Wedangan Pendopo',
                'slug' => 'wedangan-pendopo',
                'description' => 'Tempat ngopi modern dengan konsep tradisional. Menyajikan berbagai minuman wedang dan kopi dengan suasana yang nyaman.',
                'location' => 'Jl. Slamet Riyadi',
                'address' => 'Jl. Slamet Riyadi No. 456, Solo',
                'latitude' => -7.5689,
                'longitude' => 110.8156,
                'image' => 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 15.000 - 45.000',
                'since' => 'Sejak 2015',
                'facilities' => 'WiFi, AC, Parking, Outdoor seating',
                'highlights' => 'Modern cafe, Traditional drinks, Instagram-worthy',
                'opening_hours' => '10:00 - 23:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 2341,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Selat Solo Mbak Lies',
                'slug' => 'selat-solo-mbak-lies',
                'description' => 'Selat Solo adalah makanan khas Solo yang mirip bistik. Disajikan dengan daging, kentang, wortel, dan saus cokelat yang manis.',
                'location' => 'Jl. Yosodipuro',
                'address' => 'Jl. Yosodipuro No. 78, Solo',
                'latitude' => -7.5723,
                'longitude' => 110.8245,
                'image' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 25.000 - 45.000',
                'since' => 'Sejak 1985',
                'facilities' => 'Dine-in, Takeaway, Parking',
                'highlights' => 'Solo specialty, Sweet sauce, Tender meat',
                'opening_hours' => '11:00 - 21:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 1123,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Gudeg Yu Djum',
                'slug' => 'gudeg-yu-djum',
                'description' => 'Gudeg khas Yogya yang sudah terkenal hingga Solo. Gudeg manis dengan ayam kampung dan sambal krecek yang pedas.',
                'location' => 'Jl. Dr. Rajiman',
                'address' => 'Jl. Dr. Rajiman No. 12, Solo',
                'latitude' => -7.5834,
                'longitude' => 110.8123,
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 18.000 - 35.000',
                'since' => 'Sejak 1950',
                'facilities' => 'Dine-in, Takeaway, Parking',
                'highlights' => 'Sweet gudeg, Traditional recipe, Authentic taste',
                'opening_hours' => '06:00 - 14:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 2456,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Bakso Pak Kumis',
                'slug' => 'bakso-pak-kumis',
                'description' => 'Bakso legendaris dengan kuah yang gurih dan bakso yang kenyal. Sudah menjadi favorit warga Solo sejak puluhan tahun.',
                'location' => 'Jl. Brigjen Slamet Riyadi',
                'address' => 'Jl. Brigjen Slamet Riyadi No. 234, Solo',
                'latitude' => -7.5567,
                'longitude' => 110.8234,
                'image' => 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 12.000 - 25.000',
                'since' => 'Sejak 1980',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Chewy meatballs, Rich broth, Affordable price',
                'opening_hours' => '10:00 - 21:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 1789,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Es Dawet Ayu Telasih',
                'slug' => 'es-dawet-ayu-telasih',
                'description' => 'Es dawet tradisional dengan santan kelapa muda dan gula merah. Minuman segar yang cocok untuk cuaca panas Solo.',
                'location' => 'Pasar Klewer',
                'address' => 'Pasar Klewer, Jl. Secang, Solo',
                'latitude' => -7.5756,
                'longitude' => 110.8289,
                'image' => 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 8.000 - 15.000',
                'since' => 'Sejak 1970',
                'facilities' => 'Takeaway, Street vendor',
                'highlights' => 'Traditional drink, Coconut milk, Palm sugar',
                'opening_hours' => '08:00 - 17:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 1234,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Soto Gading',
                'slug' => 'soto-gading',
                'description' => 'Soto ayam khas Solo dengan kuah bening yang segar. Disajikan dengan nasi, kerupuk, dan sambal yang pedas.',
                'location' => 'Jl. Gading',
                'address' => 'Jl. Gading No. 45, Solo',
                'latitude' => -7.5612,
                'longitude' => 110.8178,
                'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 15.000 - 25.000',
                'since' => 'Sejak 1965',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Clear broth, Fresh taste, Traditional recipe',
                'opening_hours' => '07:00 - 15:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 987,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Pecel Madiun Pak Gendut',
                'slug' => 'pecel-madiun-pak-gendut',
                'description' => 'Pecel khas Madiun dengan bumbu kacang yang gurih dan pedas. Disajikan dengan sayuran segar dan kerupuk.',
                'location' => 'Jl. Veteran',
                'address' => 'Jl. Veteran No. 67, Solo',
                'latitude' => -7.5689,
                'longitude' => 110.8234,
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 10.000 - 20.000',
                'since' => 'Sejak 1990',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Peanut sauce, Fresh vegetables, Healthy option',
                'opening_hours' => '06:00 - 14:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 678,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Tengkleng Gajah',
                'slug' => 'tengkleng-gajah',
                'description' => 'Tengkleng kambing dengan kuah yang gurih dan daging yang empuk. Cocok dinikmati saat cuaca dingin.',
                'location' => 'Jl. Diponegoro',
                'address' => 'Jl. Diponegoro No. 89, Solo',
                'latitude' => -7.5723,
                'longitude' => 110.8245,
                'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 25.000 - 45.000',
                'since' => 'Sejak 1975',
                'facilities' => 'Dine-in, Parking',
                'highlights' => 'Goat meat, Rich broth, Warming dish',
                'opening_hours' => '17:00 - 23:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 1456,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Nasi Gudeg Bu Kasno',
                'slug' => 'nasi-gudeg-bu-kasno',
                'description' => 'Gudeg Solo dengan cita rasa yang lebih gurih dibanding gudeg Yogya. Disajikan dengan ayam, telur, dan sambal goreng krecek.',
                'location' => 'Jl. Teuku Umar',
                'address' => 'Jl. Teuku Umar No. 234, Solo',
                'latitude' => -7.5678,
                'longitude' => 110.8234,
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 20.000 - 35.000',
                'since' => 'Sejak 1985',
                'facilities' => 'Dine-in, Takeaway, Parking',
                'highlights' => 'Solo style gudeg, Savory taste, Complete meal',
                'opening_hours' => '06:00 - 15:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 1234,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Warung Babi Guling Pak Malen',
                'slug' => 'warung-babi-guling-pak-malen',
                'description' => 'Babi guling khas Bali yang sudah terkenal di Solo. Daging babi yang empuk dengan bumbu rempah yang khas.',
                'location' => 'Jl. Adisucipto',
                'address' => 'Jl. Adisucipto No. 123, Solo',
                'latitude' => -7.5456,
                'longitude' => 110.8345,
                'image' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 30.000 - 55.000',
                'since' => 'Sejak 2000',
                'facilities' => 'Dine-in, Takeaway, AC',
                'highlights' => 'Balinese cuisine, Tender pork, Spiced marinade',
                'opening_hours' => '11:00 - 21:00',
                'is_halal' => false,
                'is_featured' => true,
                'views' => 987,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Ayam Goreng Mbok Berek',
                'slug' => 'ayam-goreng-mbok-berek',
                'description' => 'Ayam goreng dengan bumbu tradisional yang meresap hingga ke dalam. Disajikan dengan nasi hangat dan lalapan.',
                'location' => 'Jl. Dr. Moewardi',
                'address' => 'Jl. Dr. Moewardi No. 56, Solo',
                'latitude' => -7.5589,
                'longitude' => 110.8456,
                'image' => 'https://images.unsplash.com/photo-1562967914-608f82629710?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 18.000 - 30.000',
                'since' => 'Sejak 1978',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Crispy chicken, Traditional spices, Home-style cooking',
                'opening_hours' => '10:00 - 20:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 1345,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Gado-gado Bon Bin',
                'slug' => 'gado-gado-bon-bin',
                'description' => 'Gado-gado dengan sayuran segar dan bumbu kacang yang gurih. Menu sehat yang cocok untuk vegetarian.',
                'location' => 'Jl. Ronggowarsito',
                'address' => 'Jl. Ronggowarsito No. 78, Solo',
                'latitude' => -7.5697,
                'longitude' => 110.8114,
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 12.000 - 22.000',
                'since' => 'Sejak 1995',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Fresh vegetables, Peanut sauce, Vegetarian friendly',
                'opening_hours' => '08:00 - 16:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 789,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Sate Kambing Pak Bejo',
                'slug' => 'sate-kambing-pak-bejo',
                'description' => 'Sate kambing dengan daging yang empuk dan bumbu kacang yang gurih. Cocok untuk pecinta daging kambing.',
                'location' => 'Jl. Urip Sumoharjo',
                'address' => 'Jl. Urip Sumoharjo No. 123, Solo',
                'latitude' => -7.5712,
                'longitude' => 110.8267,
                'image' => 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 20.000 - 40.000',
                'since' => 'Sejak 1988',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Tender goat meat, Peanut sauce, Grilled perfection',
                'opening_hours' => '17:00 - 23:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 1123,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Rawon Setan',
                'slug' => 'rawon-setan',
                'description' => 'Rawon dengan kuah hitam yang khas dan daging sapi yang empuk. Disajikan dengan tauge dan kerupuk udang.',
                'location' => 'Jl. Slamet Riyadi',
                'address' => 'Jl. Slamet Riyadi No. 345, Solo',
                'latitude' => -7.5689,
                'longitude' => 110.8156,
                'image' => 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 22.000 - 35.000',
                'since' => 'Sejak 1992',
                'facilities' => 'Dine-in, Takeaway, AC',
                'highlights' => 'Black soup, Tender beef, East Javanese cuisine',
                'opening_hours' => '11:00 - 21:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 1456,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Bakmi Jawa Pak Gareng',
                'slug' => 'bakmi-jawa-pak-gareng',
                'description' => 'Bakmi Jawa dengan mie yang kenyal dan bumbu yang meresap. Disajikan dengan ayam suwir dan sayuran.',
                'location' => 'Jl. Kapten Mulyadi',
                'address' => 'Jl. Kapten Mulyadi No. 67, Solo',
                'latitude' => -7.5645,
                'longitude' => 110.8198,
                'image' => 'https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 15.000 - 28.000',
                'since' => 'Sejak 1983',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Javanese noodles, Chewy texture, Traditional flavor',
                'opening_hours' => '09:00 - 20:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 987,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Nasi Pecel Bu Tinuk',
                'slug' => 'nasi-pecel-bu-tinuk',
                'description' => 'Nasi pecel dengan sayuran rebus dan bumbu pecel yang pedas. Menu sehat dan bergizi untuk sarapan.',
                'location' => 'Jl. Ahmad Yani',
                'address' => 'Jl. Ahmad Yani No. 89, Solo',
                'latitude' => -7.5534,
                'longitude' => 110.8289,
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 8.000 - 18.000',
                'since' => 'Sejak 1998',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Boiled vegetables, Spicy peanut sauce, Healthy meal',
                'opening_hours' => '06:00 - 13:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 567,
            ],
            [
                'category_id' => 3, // Kuliner
                'name' => 'Warung Tahu Gimbal Pak Mahmud',
                'slug' => 'warung-tahu-gimbal-pak-mahmud',
                'description' => 'Tahu gimbal khas Semarang yang sudah terkenal di Solo. Tahu goreng dengan udang dan sayuran segar.',
                'location' => 'Jl. Jenderal Sudirman',
                'address' => 'Jl. Jenderal Sudirman No. 123, Solo',
                'latitude' => -7.5612,
                'longitude' => 110.8345,
                'image' => 'https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=800',
                'rating' => 0.0,
                'total_reviews' => 0,
                'price_range' => 'Rp 12.000 - 25.000',
                'since' => 'Sejak 2005',
                'facilities' => 'Dine-in, Takeaway',
                'highlights' => 'Fried tofu, Shrimp fritters, Semarang specialty',
                'opening_hours' => '10:00 - 19:00',
                'is_halal' => true,
                'is_featured' => true,
                'views' => 789,
            ],
        ];

        foreach ($culinaries as $culinary) {
            Culinary::firstOrCreate(['slug' => $culinary['slug']], $culinary);
        }
    }
}