<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Destination;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            [
                'category_id' => 1, // Wisata Alam
                'name' => 'Grojogan Sewu',
                'slug' => 'grojogan-sewu',
                'description' => 'Grojogan Sewu adalah air terjun yang terletak di Tawangmangu, Karanganyar. Air terjun setinggi 120 meter ini dikelilingi oleh hutan pinus yang sejuk dan asri.',
                'location' => 'Tawangmangu, Karanganyar',
                'address' => 'Jl. Grojogan Sewu, Tawangmangu, Karanganyar',
                'latitude' => -7.6789,
                'longitude' => 111.1234,
                'image' => 'https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800',
                'rating' => 4.8,
                'total_reviews' => 245,
                'ticket_price' => 'Rp 15.000',
                'facilities' => 'Parking, Toilet, Restaurant, Prayer Room',
                'highlights' => '120m waterfall, Natural pool, Hiking trails',
                'opening_hours' => '08:00 - 17:00',
                'is_featured' => true,
                'views' => 1523,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Keraton Surakarta',
                'slug' => 'keraton-surakarta',
                'description' => 'Keraton Surakarta Hadiningrat adalah istana resmi Kesunanan Surakarta yang terletak di Kota Solo. Dibangun pada tahun 1745, keraton ini menjadi pusat kebudayaan Jawa.',
                'location' => 'Solo Tengah, Surakarta',
                'address' => 'Jl. Kamandungan, Baluwarti, Kec. Ps. Kliwon, Kota Surakarta',
                'latitude' => -7.5833,
                'longitude' => 110.8264,
                'image' => 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800',
                'rating' => 4.9,
                'total_reviews' => 892,
                'ticket_price' => 'Rp 20.000',
                'facilities' => 'Museum, Guide, Parking, Toilet',
                'highlights' => 'Javanese palace, Cultural heritage, Traditional ceremonies',
                'opening_hours' => '09:00 - 15:00',
                'is_featured' => true,
                'views' => 3421,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Pura Mangkunegaran',
                'slug' => 'pura-mangkunegaran',
                'description' => 'Pura Mangkunegaran adalah istana Kadipaten Mangkunegaran yang terletak di Kota Solo. Istana ini memiliki arsitektur yang indah dan koleksi pusaka yang berharga.',
                'location' => 'Solo Tengah, Surakarta',
                'address' => 'Jl. Ronggowarsito No.150, Keprabon, Kec. Banjarsari, Kota Surakarta',
                'latitude' => -7.5697,
                'longitude' => 110.8114,
                'image' => 'https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800',
                'rating' => 4.7,
                'total_reviews' => 456,
                'ticket_price' => 'Rp 25.000',
                'facilities' => 'Museum, Guide, Parking',
                'highlights' => 'Royal palace, Antique collections, Traditional dance',
                'opening_hours' => '09:00 - 14:00',
                'is_featured' => true,
                'views' => 2134,
            ],
            [
                'category_id' => 4, // Belanja
                'name' => 'Pasar Klewer',
                'slug' => 'pasar-klewer',
                'description' => 'Pasar Klewer adalah pasar tradisional terbesar di Solo yang menjual berbagai macam batik dan tekstil. Pasar ini menjadi pusat perdagangan batik di Solo.',
                'location' => 'Solo Tengah, Surakarta',
                'address' => 'Jl. Secang, Gajahan, Kec. Ps. Kliwon, Kota Surakarta',
                'latitude' => -7.5756,
                'longitude' => 110.8289,
                'image' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
                'rating' => 4.5,
                'total_reviews' => 678,
                'ticket_price' => 'Free',
                'facilities' => 'Parking, Toilet, ATM',
                'highlights' => 'Batik shopping, Traditional market, Affordable prices',
                'opening_hours' => '08:00 - 17:00',
                'is_featured' => true,
                'views' => 1876,
            ],
            [
                'category_id' => 1, // Wisata Alam
                'name' => 'Taman Balekambang',
                'slug' => 'taman-balekambang',
                'description' => 'Taman Balekambang adalah taman rekreasi yang memiliki danau buatan dengan pulau di tengahnya. Taman ini cocok untuk bersantai dan piknik bersama keluarga.',
                'location' => 'Solo, Surakarta',
                'address' => 'Jl. Balekambang, Manahan, Kec. Banjarsari, Kota Surakarta',
                'latitude' => -7.5589,
                'longitude' => 110.8456,
                'image' => 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=800',
                'rating' => 4.6,
                'total_reviews' => 523,
                'ticket_price' => 'Rp 10.000',
                'facilities' => 'Playground, Boat rental, Restaurant, Parking',
                'highlights' => 'Lake view, Island pavilion, Family friendly',
                'opening_hours' => '06:00 - 18:00',
                'is_featured' => true,
                'views' => 987,
            ],
            [
                'category_id' => 1, // Wisata Alam
                'name' => 'Kebun Binatang Jurug',
                'slug' => 'kebun-binatang-jurug',
                'description' => 'Kebun Binatang Jurug adalah kebun binatang yang terletak di Solo. Tempat ini memiliki berbagai koleksi satwa dan wahana rekreasi untuk keluarga.',
                'location' => 'Jurug, Surakarta',
                'address' => 'Jl. Ir. Sutami No. 295, Jurug, Surakarta',
                'latitude' => -7.5234,
                'longitude' => 110.8567,
                'image' => 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800',
                'rating' => 4.4,
                'total_reviews' => 789,
                'ticket_price' => 'Rp 25.000',
                'facilities' => 'Parking, Toilet, Restaurant, Playground',
                'highlights' => 'Animal collection, Family friendly, Educational',
                'opening_hours' => '08:00 - 16:00',
                'is_featured' => true,
                'views' => 1456,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Museum Radya Pustaka',
                'slug' => 'museum-radya-pustaka',
                'description' => 'Museum Radya Pustaka adalah museum tertua di Indonesia yang didirikan pada tahun 1890. Museum ini menyimpan koleksi benda-benda bersejarah Jawa.',
                'location' => 'Solo Tengah, Surakarta',
                'address' => 'Jl. Slamet Riyadi No. 275, Sriwedari, Surakarta',
                'latitude' => -7.5678,
                'longitude' => 110.8123,
                'image' => 'https://images.unsplash.com/photo-1566127992631-137a642a90f4?w=800',
                'rating' => 4.3,
                'total_reviews' => 234,
                'ticket_price' => 'Rp 5.000',
                'facilities' => 'Guide, Parking, Toilet',
                'highlights' => 'Historical artifacts, Oldest museum, Javanese culture',
                'opening_hours' => '08:00 - 15:00',
                'is_featured' => true,
                'views' => 567,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Masjid Agung Surakarta',
                'slug' => 'masjid-agung-surakarta',
                'description' => 'Masjid Agung Surakarta adalah masjid bersejarah yang dibangun pada tahun 1763. Masjid ini memiliki arsitektur Jawa yang khas dan menjadi pusat kegiatan keagamaan.',
                'location' => 'Solo Tengah, Surakarta',
                'address' => 'Jl. Alun-Alun Utara, Baluwarti, Surakarta',
                'latitude' => -7.5812,
                'longitude' => 110.8278,
                'image' => 'https://images.unsplash.com/photo-1564769625392-651b2c0e7b8b?w=800',
                'rating' => 4.8,
                'total_reviews' => 456,
                'ticket_price' => 'Free',
                'facilities' => 'Parking, Toilet, Prayer room',
                'highlights' => 'Historical mosque, Javanese architecture, Religious site',
                'opening_hours' => '05:00 - 21:00',
                'is_featured' => true,
                'views' => 1234,
            ],
            [
                'category_id' => 4, // Belanja
                'name' => 'Solo Grand Mall',
                'slug' => 'solo-grand-mall',
                'description' => 'Solo Grand Mall adalah pusat perbelanjaan modern di Solo yang menyediakan berbagai toko, restoran, dan hiburan untuk keluarga.',
                'location' => 'Banjarsari, Surakarta',
                'address' => 'Jl. Slamet Riyadi No. 451, Pajang, Surakarta',
                'latitude' => -7.5456,
                'longitude' => 110.8345,
                'image' => 'https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800',
                'rating' => 4.2,
                'total_reviews' => 1234,
                'ticket_price' => 'Free',
                'facilities' => 'Parking, Food court, Cinema, ATM',
                'highlights' => 'Modern shopping, Entertainment, Food court',
                'opening_hours' => '10:00 - 22:00',
                'is_featured' => true,
                'views' => 2345,
            ],
            [
                'category_id' => 1, // Wisata Alam
                'name' => 'Taman Sriwedari',
                'slug' => 'taman-sriwedari',
                'description' => 'Taman Sriwedari adalah taman hiburan rakyat yang terletak di pusat kota Solo. Taman ini memiliki berbagai wahana permainan dan pertunjukan wayang orang.',
                'location' => 'Solo Tengah, Surakarta',
                'address' => 'Jl. Slamet Riyadi, Sriwedari, Surakarta',
                'latitude' => -7.5689,
                'longitude' => 110.8156,
                'image' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800',
                'rating' => 4.1,
                'total_reviews' => 678,
                'ticket_price' => 'Rp 5.000',
                'facilities' => 'Parking, Food stalls, Playground, Theater',
                'highlights' => 'Traditional theater, Family entertainment, Cultural shows',
                'opening_hours' => '16:00 - 22:00',
                'is_featured' => true,
                'views' => 1567,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Benteng Vastenburg',
                'slug' => 'benteng-vastenburg',
                'description' => 'Benteng Vastenburg adalah benteng peninggalan Belanda yang dibangun pada tahun 1745. Kini benteng ini menjadi museum dan tempat wisata sejarah.',
                'location' => 'Solo Tengah, Surakarta',
                'address' => 'Jl. Kapten Mulyadi, Kedung Lumbu, Surakarta',
                'latitude' => -7.5645,
                'longitude' => 110.8198,
                'image' => 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=800',
                'rating' => 4.0,
                'total_reviews' => 345,
                'ticket_price' => 'Rp 10.000',
                'facilities' => 'Museum, Guide, Parking',
                'highlights' => 'Dutch fortress, Historical site, Colonial architecture',
                'opening_hours' => '08:00 - 16:00',
                'is_featured' => true,
                'views' => 789,
            ],
            [
                'category_id' => 1, // Wisata Alam
                'name' => 'Waduk Cengklik',
                'slug' => 'waduk-cengklik',
                'description' => 'Waduk Cengklik adalah waduk yang terletak di Boyolali, dekat Solo. Tempat ini cocok untuk memancing, berperahu, dan menikmati pemandangan alam.',
                'location' => 'Boyolali',
                'address' => 'Cengklik, Boyolali',
                'latitude' => -7.4567,
                'longitude' => 110.7234,
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
                'rating' => 4.3,
                'total_reviews' => 456,
                'ticket_price' => 'Rp 5.000',
                'facilities' => 'Parking, Boat rental, Restaurant',
                'highlights' => 'Lake view, Fishing, Boating',
                'opening_hours' => '06:00 - 18:00',
                'is_featured' => true,
                'views' => 1123,
            ],
            [
                'category_id' => 4, // Belanja
                'name' => 'Pasar Triwindu',
                'slug' => 'pasar-triwindu',
                'description' => 'Pasar Triwindu adalah pasar antik yang menjual berbagai barang antik dan kerajinan tradisional. Tempat ini menjadi surga bagi kolektor barang antik.',
                'location' => 'Solo Tengah, Surakarta',
                'address' => 'Jl. Diponegoro, Keprabon, Surakarta',
                'latitude' => -7.5723,
                'longitude' => 110.8245,
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
                'rating' => 4.4,
                'total_reviews' => 234,
                'ticket_price' => 'Free',
                'facilities' => 'Parking, Toilet',
                'highlights' => 'Antique market, Traditional crafts, Unique finds',
                'opening_hours' => '08:00 - 16:00',
                'is_featured' => true,
                'views' => 678,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Kampung Batik Laweyan',
                'slug' => 'kampung-batik-laweyan',
                'description' => 'Kampung Batik Laweyan adalah sentra industri batik tradisional di Solo. Pengunjung dapat melihat proses pembuatan batik dan berbelanja batik langsung dari pengrajin.',
                'location' => 'Laweyan, Surakarta',
                'address' => 'Jl. Dr. Rajiman, Laweyan, Surakarta',
                'latitude' => -7.5834,
                'longitude' => 110.8123,
                'image' => 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800',
                'rating' => 4.6,
                'total_reviews' => 567,
                'ticket_price' => 'Free',
                'facilities' => 'Workshop, Gallery, Parking',
                'highlights' => 'Batik making, Traditional craft, Cultural heritage',
                'opening_hours' => '08:00 - 17:00',
                'is_featured' => true,
                'views' => 1456,
            ],
            [
                'category_id' => 1, // Wisata Alam
                'name' => 'Hutan Pinus Pengger',
                'slug' => 'hutan-pinus-pengger',
                'description' => 'Hutan Pinus Pengger adalah destinasi wisata alam yang menawarkan pemandangan hutan pinus yang indah dan udara yang sejuk.',
                'location' => 'Karanganyar',
                'address' => 'Pengger, Karanganyar',
                'latitude' => -7.6234,
                'longitude' => 111.0567,
                'image' => 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
                'rating' => 4.5,
                'total_reviews' => 345,
                'ticket_price' => 'Rp 10.000',
                'facilities' => 'Parking, Toilet, Photo spots',
                'highlights' => 'Pine forest, Fresh air, Photography',
                'opening_hours' => '06:00 - 18:00',
                'is_featured' => true,
                'views' => 987,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Rumah Atsiri Indonesia',
                'slug' => 'rumah-atsiri-indonesia',
                'description' => 'Rumah Atsiri Indonesia adalah museum dan pusat edukasi tentang minyak atsiri. Tempat ini menampilkan berbagai tanaman penghasil minyak atsiri dan proses pembuatannya.',
                'location' => 'Tawangmangu, Karanganyar',
                'address' => 'Jl. Raya Tawangmangu, Karanganyar',
                'latitude' => -7.6789,
                'longitude' => 111.1234,
                'image' => 'https://images.unsplash.com/photo-1574263867128-a3d5c1b1deaa?w=800',
                'rating' => 4.2,
                'total_reviews' => 123,
                'ticket_price' => 'Rp 15.000',
                'facilities' => 'Museum, Garden, Workshop, Parking',
                'highlights' => 'Essential oils, Educational tour, Herbal garden',
                'opening_hours' => '08:00 - 16:00',
                'is_featured' => true,
                'views' => 456,
            ],
            [
                'category_id' => 4, // Belanja
                'name' => 'Solo Paragon Mall',
                'slug' => 'solo-paragon-mall',
                'description' => 'Solo Paragon Mall adalah pusat perbelanjaan modern yang menyediakan berbagai brand internasional dan lokal, serta fasilitas hiburan lengkap.',
                'location' => 'Banjarsari, Surakarta',
                'address' => 'Jl. Yosodipuro No. 135, Surakarta',
                'latitude' => -7.5567,
                'longitude' => 110.8234,
                'image' => 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=800',
                'rating' => 4.3,
                'total_reviews' => 890,
                'ticket_price' => 'Free',
                'facilities' => 'Parking, Food court, Cinema, Playground',
                'highlights' => 'Modern shopping, International brands, Entertainment',
                'opening_hours' => '10:00 - 22:00',
                'is_featured' => true,
                'views' => 1789,
            ],
            [
                'category_id' => 1, // Wisata Alam
                'name' => 'Telaga Madirda',
                'slug' => 'telaga-madirda',
                'description' => 'Telaga Madirda adalah danau alami yang terletak di lereng Gunung Lawu. Tempat ini menawarkan pemandangan alam yang indah dan udara yang sejuk.',
                'location' => 'Magetan',
                'address' => 'Plaosan, Magetan',
                'latitude' => -7.7234,
                'longitude' => 111.2567,
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
                'rating' => 4.4,
                'total_reviews' => 234,
                'ticket_price' => 'Rp 8.000',
                'facilities' => 'Parking, Toilet, Gazebo',
                'highlights' => 'Natural lake, Mountain view, Cool weather',
                'opening_hours' => '06:00 - 18:00',
                'is_featured' => true,
                'views' => 567,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Candi Sukuh',
                'slug' => 'candi-sukuh',
                'description' => 'Candi Sukuh adalah candi Hindu yang terletak di lereng Gunung Lawu. Candi ini memiliki bentuk yang unik seperti piramid dan relief yang menarik.',
                'location' => 'Karanganyar',
                'address' => 'Berjo, Ngargoyoso, Karanganyar',
                'latitude' => -7.6345,
                'longitude' => 111.1456,
                'image' => 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800',
                'rating' => 4.7,
                'total_reviews' => 456,
                'ticket_price' => 'Rp 15.000',
                'facilities' => 'Parking, Toilet, Guide',
                'highlights' => 'Ancient temple, Pyramid shape, Mountain location',
                'opening_hours' => '07:00 - 17:00',
                'is_featured' => true,
                'views' => 1234,
            ],
            [
                'category_id' => 2, // Budaya
                'name' => 'Candi Cetho',
                'slug' => 'candi-cetho',
                'description' => 'Candi Cetho adalah candi Hindu yang terletak di lereng Gunung Lawu. Candi ini menawarkan pemandangan yang spektakuler dan suasana yang mistis.',
                'location' => 'Karanganyar',
                'address' => 'Gumeng, Ngargoyoso, Karanganyar',
                'latitude' => -7.6456,
                'longitude' => 111.1567,
                'image' => 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800',
                'rating' => 4.6,
                'total_reviews' => 345,
                'ticket_price' => 'Rp 15.000',
                'facilities' => 'Parking, Toilet, Guide',
                'highlights' => 'Ancient temple, Mountain view, Mystical atmosphere',
                'opening_hours' => '07:00 - 17:00',
                'is_featured' => true,
                'views' => 987,
            ],
            [
                'category_id' => 4, // Belanja
                'name' => 'The Park Mall Solo',
                'slug' => 'the-park-mall-solo',
                'description' => 'The Park Mall Solo adalah pusat perbelanjaan terbaru di Solo dengan konsep outdoor yang unik. Mall ini menyediakan berbagai toko dan restoran.',
                'location' => 'Banjarsari, Surakarta',
                'address' => 'Jl. Ir. Sutami No. 62, Surakarta',
                'latitude' => -7.5678,
                'longitude' => 110.8345,
                'image' => 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=800',
                'rating' => 4.1,
                'total_reviews' => 567,
                'ticket_price' => 'Free',
                'facilities' => 'Parking, Food court, Outdoor area',
                'highlights' => 'Outdoor concept, Modern design, Dining options',
                'opening_hours' => '10:00 - 22:00',
                'is_featured' => true,
                'views' => 1345,
            ],
        ];

        foreach ($destinations as $destination) {
            Destination::firstOrCreate(['slug' => $destination['slug']], $destination);
        }
    }
}